services:
    db:
        image: postgres
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel_portfolio_music
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    php:
        container_name: php
        build:
            context: ./src
        ports:
            - "80:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        volumes:
            - ./src:/var/www/html
            # - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - db
