FROM node:16-slim as node-builder

COPY . ./app
RUN cd /app && npm install && npm run build

FROM php:8.2-apache as production

RUN apt update && apt install -y zlib1g-dev g++ libicu-dev zip libzip-dev zip libpq-dev \
    && docker-php-ext-install intl opcache pdo pgsql pdo_pgsql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && apt-get install -y git \
    && a2enmod rewrite

RUN echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf
RUN a2enconf fqdn

WORKDIR /var/www/html

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

COPY . ./
COPY --from=node-builder /app/public ./public
RUN composer install

RUN chown -Rf www-data:www-data ./

# for development

FROM php:8.2-apache

RUN apt update && apt install -y zlib1g-dev g++ libicu-dev zip libzip-dev zip libpq-dev \
    && docker-php-ext-install intl opcache pdo pgsql pdo_pgsql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && apt-get install -y git \
    && a2enmod rewrite

RUN echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf
RUN a2enconf fqdn

RUN curl -sL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get install -y nodejs
RUN npm install -y npm@latest -g

WORKDIR /var/www/html

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

COPY . ./

RUN composer install
RUN npm install

RUN chown -Rf www-data:www-data ./
